use_frameworks!

target 'EasyMakePhotoPicker_Example' do
  pod 'EasyMakePhotoPicker', :path => '../'
  pod 'RxSwift'
  pod 'RxCocoa'
 
  target 'EasyMakePhotoPicker_Tests' do
    inherit! :search_paths
    pod 'RxSwift'
    pod 'RxCocoa'
  end
end
